### ISSUE TITLE
Modify floor price command to display more info on NFT collection

### ISSUE THREAD

**Issue by ChristianPerez34** [Stonks-Luma-Liberty/Plutus#10]

**Comment by Tabinka** [comment]
@ChristianPerez34  Hi, can I work on this issue? It would be my first time contributing and I want to try it. :)

**Comment by ChristianPerez34** [comment]
Sure thing and looking forward to it. Excited someone wants to take part :)

**Comment by Tabinka** [comment]
Do you have a discord where I can DM you? I have some problems with running the bot on a test server. Could you help me with that? Thanks :)

**Comment by ChristianPerez34** [comment]
> Do you have a discord where I can DM you? I have some problems with running the bot on a test server. Could you help me with that? Thanks :) 

Sure thing! 

Here is my discord: LifeLineLogics#8875

Feel free to ask me any questions and I'll be glad to help
